disabled_rules:
- force_try

opt_in_rules:
  - convenience_type
  - empty_count
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - prohibited_interface_builder
  - toggle_bool
  - unused_private_declaration
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - unavailable_function
  - overridden_super_call

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
  
identifier_name:
  allowed_symbols: "_"

line_length:
  error: 120
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 300
  error: 500

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  error: 500
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode"
